// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALUbqh0XWhl_FiRLjVcODiDMNCWj2FRVw',
    appId: '1:21555634009:web:32804f0f129598bed9f648',
    messagingSenderId: '21555634009',
    projectId: 'fsnsjbdkvjsnbjdb',
    authDomain: 'fsnsjbdkvjsnbjdb.firebaseapp.com',
    storageBucket: 'fsnsjbdkvjsnbjdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYFE65RyV4-nmkgJYWMsXhPAay9N-fvjE',
    appId: '1:21555634009:android:3199c77a901b2e8ed9f648',
    messagingSenderId: '21555634009',
    projectId: 'fsnsjbdkvjsnbjdb',
    storageBucket: 'fsnsjbdkvjsnbjdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6DIqa-UMlcDnCdtwA7PYq_X4NwPBpZvU',
    appId: '1:21555634009:ios:3a1b59a8c6fa0679d9f648',
    messagingSenderId: '21555634009',
    projectId: 'fsnsjbdkvjsnbjdb',
    storageBucket: 'fsnsjbdkvjsnbjdb.appspot.com',
    iosClientId: '21555634009-hpgrt55bsp1tisf9qmejvj21npjm660g.apps.googleusercontent.com',
    iosBundleId: 'com.example.three',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6DIqa-UMlcDnCdtwA7PYq_X4NwPBpZvU',
    appId: '1:21555634009:ios:3a1b59a8c6fa0679d9f648',
    messagingSenderId: '21555634009',
    projectId: 'fsnsjbdkvjsnbjdb',
    storageBucket: 'fsnsjbdkvjsnbjdb.appspot.com',
    iosClientId: '21555634009-hpgrt55bsp1tisf9qmejvj21npjm660g.apps.googleusercontent.com',
    iosBundleId: 'com.example.three',
  );
}
